spring:
  application:
    #项目名称
    name: order
    #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101:3306/sell?characterEncoding=utf-8&useSSL=false
  #jpa显示sql
  jpa:
    show-sql: true
eureka:
  instance:
    #以IP方式注册
    prefer-ip-address: true
  client:
    service-url:
      #注册地址
      defaultZone: http://172.16.10.200:8761/eureka/
server:
  #项目端口
  port: 8081
  servlet:
    context-path: /order
